[build]
  publish = "public"
  command = "echo ok"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    compat = false